import { StyleSheet } from "react-native";

export const PaymentExpenseStyle = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#daecf9ff' },
  addButton: {
    backgroundColor: '#040b51ff',
    margin: 15,
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  addButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  tableContainer: { marginHorizontal: 10 },
  tableRow: { flexDirection: 'row', alignItems: 'center' },
  column: { flex: 1, alignItems: 'center', paddingHorizontal: 4 },
  columnTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
    textAlign: 'center',
  },
  columnValue: {
    fontSize: 12,
    color: '#222',
    flexWrap: 'wrap',
    textAlign: 'center',
  },
  emptyText: {
    textAlign: 'center',
    marginTop: '50%',
    color: '#000',
    fontSize: 20,
    fontWeight: "bold"
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 20,
  },
  modalContainer: { backgroundColor: '#fff', borderRadius: 10, padding: 15 },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
    fontSize: 14,
    color: "#000"
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  statusButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: '#ccc',
    margin: 2,
  },
  statusText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  cancelButton: {
    marginRight: 10,
    backgroundColor: '#1E90FF',
    borderRadius: 6,
    paddingHorizontal: 15,
    paddingVertical: 6,
  },
  cancelText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  saveButton: {
    backgroundColor: '#1E90FF',
    borderRadius: 6,
    paddingHorizontal: 15,
    paddingVertical: 6,
  },
  saveText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  cardContainer: {
    marginHorizontal: 20,
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 1.5,
    elevation: 2,
  },
  fieldLabel: {
    fontWeight: '600',
    color: '#333',
    fontSize: 14,
  },
  fieldText: {
    fontSize: 13,
    color: '#444',
    marginBottom: 3, // reduced vertical space
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 4, // tighter layout
    gap: 10,
  },
  iconButton: {
    padding: 5,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
  },

  totalContainer: {
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 15,
  },
  totalBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f5f7fa',
    borderWidth: 1,
    borderColor: '#dcdcdc',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#750581ff',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1E90FF',
  },
});